<a href="https://colab.research.google.com/github/drewamorbordelon/DS-Unit-1-Sprint-2-Statistics/blob/master/module2/LS_DS19_122_Chi2_Tests_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment - Practice Chi^2 Tests

Use the following dataset relating to math scores of students in two different Portugese schools:

<https://archive.ics.uci.edu/ml/datasets/Student+Performance>

### 1) Load the dataset specifically relating to math scores as a new dataframe.

There are two datasets in the `student.zip` file, make sure you use `student-mat.csv`.


In [ ]:
# Importing libraries

import pandas as pd
import numpy as np
from scipy import stats

In [ ]:
!wget 'https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip'

--2020-08-11 20:48:27--  https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20478 (20K) [application/x-httpd-php]
Saving to: ‘student.zip’

student.zip         100%[===================>]  20.00K  --.-KB/s    in 0.07s   

2020-08-11 20:48:28 (284 KB/s) - ‘student.zip’ saved [20478/20478]



In [ ]:
!unzip /content/student.zip 

Archive:  /content/student.zip
replace student-mat.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: student-mat.csv         
replace student-por.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: student-por.csv         
replace student-merge.R? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: student-merge.R         
replace student.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: student.txt             


In [ ]:
# Loading the dataset
# separate values with sep=';'

df = pd.read_csv('student-mat.csv', sep=';')

print(df.shape)
df.head()

(395, 33)


school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1     GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2     GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3     GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4     GP   F   16       U     GT3       T  ...     2       5        4   6  10  10

[5 rows x 33 columns]

In [ ]:
df.tail()

school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
390     MS   M   20       U     LE3       A  ...     5       4       11   9   9   9
391     MS   M   17       U     LE3       T  ...     4       2        3  14  16  16
392     MS   M   21       R     GT3       T  ...     3       3        3  10   8   7
393     MS   M   18       R     LE3       T  ...     4       5        0  11  12  10
394     MS   M   19       U     LE3       T  ...     3       5        5   8   9   9

[5 rows x 33 columns]

In [ ]:
df.describe()

age        Medu        Fedu  ...          G1          G2          G3
count  395.000000  395.000000  395.000000  ...  395.000000  395.000000  395.000000
mean    16.696203    2.749367    2.521519  ...   10.908861   10.713924   10.415190
std      1.276043    1.094735    1.088201  ...    3.319195    3.761505    4.581443
min     15.000000    0.000000    0.000000  ...    3.000000    0.000000    0.000000
25%     16.000000    2.000000    2.000000  ...    8.000000    9.000000    8.000000
50%     17.000000    3.000000    2.000000  ...   11.000000   11.000000   11.000000
75%     18.000000    4.000000    3.000000  ...   13.000000   13.000000   14.000000
max     22.000000    4.000000    4.000000  ...   19.000000   19.000000   20.000000

[8 rows x 16 columns]

In [ ]:
df.dtypes

school        object
sex           object
age            int64
address       object
famsize       object
Pstatus       object
Medu           int64
Fedu           int64
Mjob          object
Fjob          object
reason        object
guardian      object
traveltime     int64
studytime      int64
failures       int64
schoolsup     object
famsup        object
paid          object
activities    object
nursery       object
higher        object
internet      object
romantic      object
famrel         int64
freetime       int64
goout          int64
Dalc           int64
Walc           int64
health         int64
absences       int64
G1             int64
G2             int64
G3             int64
dtype: object

In [ ]:
df.isnull().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

### 2) Use Chi^2 tests and `stats.chi2_contingency()` to identify:
 - Two pairs of variables that are dependent (are associated with one another).
 - Two pairs of variables that are independent (have no significant relationship).

Does it make intuitive sense why the variables in these pairs might or might not show a relationship to one another? 


In [ ]:
# Define the null and alternative hypothesis

***Null Hypothesis:***
There is no relationship between the two categorical variables (independent).

***Alternative Hypothesis***
There is a relationship between the two categorical variables (dependent).

In [ ]:
df.head()

school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1     GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2     GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3     GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4     GP   F   16       U     GT3       T  ...     2       5        4   6  10  10

[5 rows x 33 columns]

In [ ]:
# Create a contingency using pd.crosstab

contingency = pd.crosstab(df['Mjob'], df['studytime'], margins=True)

contingency

studytime    1    2   3   4  All
Mjob                            
at_home     13   30  13   3   59
health       9   18   5   2   34
other       38   73  18  12  141
services    30   47  19   7  103
teacher     15   30  10   3   58
All        105  198  65  27  395

In [ ]:
chi2, p_value, dof, expected = stats.chi2_contingency(contingency)

print('chi2:', chi2)
print('p-value:', p_value)
print('dof:', dof)
print('expected_frequencies: \n', expected)

chi2: 5.048287485905085
p-value: 0.9997011494888577
dof: 20
expected_frequencies: 
 [[ 15.6835443   29.57468354   9.70886076   4.03291139  59.        ]
 [  9.03797468  17.04303797   5.59493671   2.32405063  34.        ]
 [ 37.48101266  70.67848101  23.20253165   9.63797468 141.        ]
 [ 27.37974684  51.63037975  16.94936709   7.04050633 103.        ]
 [ 15.41772152  29.07341772   9.5443038    3.96455696  58.        ]
 [105.         198.          65.          27.         395.        ]]


In [ ]:
contingency = pd.crosstab(df['Fjob'], df['studytime'])

contingency

studytime   1    2   3   4
Fjob                      
at_home     4    9   7   0
health      2    8   5   3
other      58  115  29  15
services   32   51  19   9
teacher     9   15   5   0

In [ ]:
chi2, p_value, dof, expected = stats.chi2_contingency(contingency)

print("chi2:", chi2)
print("p value:", p_value)
print("dof:", dof)
print("expected_frequencies: \n", expected)

chi2: 16.39646138892259
p value: 0.17374458993358266
dof: 12
expected_frequencies: 
 [[  5.3164557   10.02531646   3.29113924   1.36708861]
 [  4.78481013   9.02278481   2.96202532   1.23037975]
 [ 57.6835443  108.77468354  35.70886076  14.83291139]
 [ 29.50632911  55.64050633  18.26582278   7.58734177]
 [  7.70886076  14.53670886   4.7721519    1.98227848]]


In [ ]:
contingency = pd.crosstab(df['sex'], df['studytime'])

contingency

studytime   1    2   3   4
sex                       
F          27  113  51  17
M          78   85  14  10

In [ ]:
chi2, p_value, dof, expected = stats.chi2_contingency(contingency)

print("chi2:", chi2)
print("p value:", p_value)
print("dof:", dof)
print("expected_frequencies: \n", expected)

chi2: 50.634037705651764
p value: 5.854045926336989e-11
dof: 3
expected_frequencies: 
 [[ 55.29113924 104.26329114  34.2278481   14.21772152]
 [ 49.70886076  93.73670886  30.7721519   12.78227848]]


***Null Hypothesis:***
There is no realtionship between the two categorical variables, guardian and studytime (independent).

***Alternative Hypothesis***
There is a relationship between the two categorical variables, guardian and studytime (dependent).

In [ ]:
contingency = pd.crosstab(df['guardian'], df['studytime'])

contingency

studytime   1    2   3   4
guardian                  
father     26   44  10  10
mother     73  137  47  16
other       6   17   8   1

In [ ]:
observed_with_margins = pd.crosstab(df['guardian'], df['studytime'], margins=True)

observed_with_margins

In [ ]:
# unpacking
chi2, p_value, dof, expected = stats.chi2_contingency(contingency)

In [ ]:
print("chi2:", chi2)
print("p value:", p_value)
print("dof:", dof)
print("expected_frequencies: \n", expected)

chi2: 7.515041507665898
p value: 0.2758269993780965
dof: 6
expected_frequencies: 
 [[ 23.92405063  45.11392405  14.81012658   6.15189873]
 [ 72.56962025 136.84556962  44.92405063  18.66075949]
 [  8.50632911  16.04050633   5.26582278   2.18734177]]


***Conclusion:*** 
Based on a chi2 statistic of 7.515 and a p-value of .276 we fail to reject the null hypothesis that guardian and studytime are independent.

### 3) Use NumPy to perform your own chi^2 test "from scratch" 

Pick any of the chi^2 tests that you ran in part 2 and try them on your own. You should get the same results that Scipy got for all four values returned from `chi2_contingency()`

In [ ]:
# Turning pandas into a numpy array using .values

In [ ]:
row_totals = df['guardian'].value_counts().sort_index().values

row_totals

array([ 90, 273,  32])

In [ ]:
column_totals = df['studytime'].value_counts().sort_index().values

column_totals

array([105, 198,  65,  27])

In [ ]:
sample_size = df.shape[0]

sample_size

395

In [ ]:
# original array was 4 x 3

expected = np.array([[0.0,0.0,0.0,0.0],
                     [0.0,0.0,0.0,0.0],
                     [0.0,0.0,0.0,0.0]])

for row_index, row in enumerate(row_totals):
  for column_index, col in enumerate(column_totals):
    # calculating the expected value
    expected_value = (row * col) / sample_size
    # put that value into the expected value table
    # at the correct location
    expected[row_index][column_index] = expected_value
    # print(expected_value, row_index, column_index)

expected


array([[ 23.92405063,  45.11392405,  14.81012658,   6.15189873],
       [ 72.56962025, 136.84556962,  44.92405063,  18.66075949],
       [  8.50632911,  16.04050633,   5.26582278,   2.18734177]])

In [ ]:
observed = contingency.values

observed

array([[ 26,  44,  10,  10],
       [ 73, 137,  47,  16],
       [  6,  17,   8,   1]])

In [ ]:
# Caluculate the Chi^2 test statistic

chi2 = ((observed - expected) ** 2 / expected).sum()

chi2

7.515041507665898

## Stretch goals:

### 1. Refactor your code so it is elegant, readable, and holds reusable code in functions.

In [ ]:
# YOUR WORK HERE



### 2. Check For Understanding - Study and write your own explanations/definitions for these topics:

- What is a sample "estimate" in statistics?

- What are hypothesis test? How are they useful?

- What is a "null hypothesis?"

- What is a p-value and what does it represent?

- What does it mean for something to be "statistically significant?"

- What is a test statistic and how does it relate to a p-value?

- What are "degrees of freedom" and how are they calculated in a 1-sample, 2-sample, and chi^2 test for independence?

## Resources

- [Interactive visualize the Chi-Squared test](https://homepage.divms.uiowa.edu/~mbognar/applets/chisq.html)
- [Calculation of Chi-Squared test statistic](https://en.wikipedia.org/wiki/Pearson%27s_chi-squared_test)
- [Visualization of a confidence interval generated by R code](https://commons.wikimedia.org/wiki/File:Confidence-interval.svg)
- [Expected value of a squared standard normal](https://math.stackexchange.com/questions/264061/expected-value-calculation-for-squared-normal-distribution) (it's 1 - which is why the expected value of a Chi-Squared with $n$ degrees of freedom is $n$, as it's the sum of $n$ squared standard normals)